<?php

	function getDialCodes() {
		$array = [
			'44' => 'UK (+44)',
			'1' => 'USA (+1)',
			'213' => 'Algeria (+213)',
			'376' => 'Andorra (+376)',
			'244' => 'Angola (+244)',
			'1264' => 'Anguilla (+1264)',
			'1268' => 'Antigua & Barbuda (+1268)',
			'54' => 'Argentina (+54)',
			'374' => 'Armenia (+374)',
			'297' => 'Aruba (+297)',
			'61' => 'Australia (+61)',
			'43' => 'Austria (+43)',
			'994' => 'Azerbaijan (+994)',
			'1242' => 'Bahamas (+1242)',
			'973' => 'Bahrain (+973)',
			'880' => 'Bangladesh (+880)',
			'1246' => 'Barbados (+1246)',
			'375' => 'Belarus (+375)',
			'32' => 'Belgium (+32)',
			'501' => 'Belize (+501)',
			'229' => 'Benin (+229)',
			'1441' => 'Bermuda (+1441)',
			'975' => 'Bhutan (+975)',
			'591' => 'Bolivia (+591)',
			'387' => 'Bosnia Herzegovina (+387)',
			'267' => 'Botswana (+267)',
			'55' => 'Brazil (+55)',
			'673' => 'Brunei (+673)',
			'359' => 'Bulgaria (+359)',
			'226' => 'Burkina Faso (+226)',
			'257' => 'Burundi (+257)',
			'855' => 'Cambodia (+855)',
			'237' => 'Cameroon (+237)',
			'1' => 'Canada (+1)',
			'238' => 'Cape Verde Islands (+238)',
			'1345' => 'Cayman Islands (+1345)',
			'236' => 'Central African Republic (+236)',
			'56' => 'Chile (+56)',
			'86' => 'China (+86)',
			'57' => 'Colombia (+57)',
			'269' => 'Comoros (+269)',
			'242' => 'Congo (+242)',
			'682' => 'Cook Islands (+682)',
			'506' => 'Costa Rica (+506)',
			'385' => 'Croatia (+385)',
			'53' => 'Cuba (+53)',
			'90392' => 'Cyprus North (+90392)',
			'357' => 'Cyprus South (+357)',
			'42' => 'Czech Republic (+42)',
			'45' => 'Denmark (+45)',
			'253' => 'Djibouti (+253)',
			'1809' => 'Dominica (+1809)',
			'1809' => 'Dominican Republic (+1809)',
			'593' => 'Ecuador (+593)',
			'20' => 'Egypt (+20)',
			'503' => 'El Salvador (+503)',
			'240' => 'Equatorial Guinea (+240)',
			'291' => 'Eritrea (+291)',
			'372' => 'Estonia (+372)',
			'251' => 'Ethiopia (+251)',
			'500' => 'Falkland Islands (+500)',
			'298' => 'Faroe Islands (+298)',
			'679' => 'Fiji (+679)',
			'358' => 'Finland (+358)',
			'33' => 'France (+33)',
			'594' => 'French Guiana (+594)',
			'689' => 'French Polynesia (+689)',
			'241' => 'Gabon (+241)',
			'220' => 'Gambia (+220)',
			'7880' => 'Georgia (+7880)',
			'49' => 'Germany (+49)',
			'233' => 'Ghana (+233)',
			'350' => 'Gibraltar (+350)',
			'30' => 'Greece (+30)',
			'299' => 'Greenland (+299)',
			'1473' => 'Grenada (+1473)',
			'590' => 'Guadeloupe (+590)',
			'671' => 'Guam (+671)',
			'502' => 'Guatemala (+502)',
			'224' => 'Guinea (+224)',
			'245' => 'Guinea - Bissau (+245)',
			'592' => 'Guyana (+592)',
			'509' => 'Haiti (+509)',
			'504' => 'Honduras (+504)',
			'852' => 'Hong Kong (+852)',
			'36' => 'Hungary (+36)',
			'354' => 'Iceland (+354)',
			'91' => 'India (+91)',
			'62' => 'Indonesia (+62)',
			'98' => 'Iran (+98)',
			'964' => 'Iraq (+964)',
			'353' => 'Ireland (+353)',
			'972' => 'Israel (+972)',
			'39' => 'Italy (+39)',
			'1876' => 'Jamaica (+1876)',
			'81' => 'Japan (+81)',
			'962' => 'Jordan (+962)',
			'7' => 'Kazakhstan (+7)',
			'254' => 'Kenya (+254)',
			'686' => 'Kiribati (+686)',
			'850' => 'Korea North (+850)',
			'82' => 'Korea South (+82)',
			'965' => 'Kuwait (+965)',
			'996' => 'Kyrgyzstan (+996)',
			'856' => 'Laos (+856)',
			'371' => 'Latvia (+371)',
			'961' => 'Lebanon (+961)',
			'266' => 'Lesotho (+266)',
			'231' => 'Liberia (+231)',
			'218' => 'Libya (+218)',
			'417' => 'Liechtenstein (+417)',
			'370' => 'Lithuania (+370)',
			'352' => 'Luxembourg (+352)',
			'853' => 'Macao (+853)',
			'389' => 'Macedonia (+389)',
			'261' => 'Madagascar (+261)',
			'265' => 'Malawi (+265)',
			'60' => 'Malaysia (+60)',
			'960' => 'Maldives (+960)',
			'223' => 'Mali (+223)',
			'356' => 'Malta (+356)',
			'692' => 'Marshall Islands (+692)',
			'596' => 'Martinique (+596)',
			'222' => 'Mauritania (+222)',
			'269' => 'Mayotte (+269)',
			'52' => 'Mexico (+52)',
			'691' => 'Micronesia (+691)',
			'373' => 'Moldova (+373)',
			'377' => 'Monaco (+377)',
			'976' => 'Mongolia (+976)',
			'1664' => 'Montserrat (+1664)',
			'212' => 'Morocco (+212)',
			'258' => 'Mozambique (+258)',
			'95' => 'Myanmar (+95)',
			'264' => 'Namibia (+264)',
			'674' => 'Nauru (+674)',
			'977' => 'Nepal (+977)',
			'31' => 'Netherlands (+31)',
			'687' => 'New Caledonia (+687)',
			'64' => 'New Zealand (+64)',
			'505' => 'Nicaragua (+505)',
			'227' => 'Niger (+227)',
			'234' => 'Nigeria (+234)',
			'683' => 'Niue (+683)',
			'672' => 'Norfolk Islands (+672)',
			'670' => 'Northern Marianas (+670)',
			'47' => 'Norway (+47)',
			'968' => 'Oman (+968)',
			'680' => 'Palau (+680)',
			'507' => 'Panama (+507)',
			'675' => 'Papua New Guinea (+675)',
			'595' => 'Paraguay (+595)',
			'51' => 'Peru (+51)',
			'63' => 'Philippines (+63)',
			'48' => 'Poland (+48)',
			'351' => 'Portugal (+351)',
			'1787' => 'Puerto Rico (+1787)',
			'974' => 'Qatar (+974)',
			'262' => 'Reunion (+262)',
			'40' => 'Romania (+40)',
			'7' => 'Russia (+7)',
			'250' => 'Rwanda (+250)',
			'378' => 'San Marino (+378)',
			'239' => 'Sao Tome & Principe (+239)',
			'966' => 'Saudi Arabia (+966)',
			'221' => 'Senegal (+221)',
			'381' => 'Serbia (+381)',
			'248' => 'Seychelles (+248)',
			'232' => 'Sierra Leone (+232)',
			'65' => 'Singapore (+65)',
			'421' => 'Slovak Republic (+421)',
			'386' => 'Slovenia (+386)',
			'677' => 'Solomon Islands (+677)',
			'252' => 'Somalia (+252)',
			'27' => 'South Africa (+27)',
			'34' => 'Spain (+34)',
			'94' => 'Sri Lanka (+94)',
			'290' => 'St. Helena (+290)',
			'1869' => 'St. Kitts (+1869)',
			'1758' => 'St. Lucia (+1758)',
			'249' => 'Sudan (+249)',
			'597' => 'Suriname (+597)',
			'268' => 'Swaziland (+268)',
			'46' => 'Sweden (+46)',
			'41' => 'Switzerland (+41)',
			'963' => 'Syria (+963)',
			'886' => 'Taiwan (+886)',
			'7' => 'Tajikstan (+7)',
			'66' => 'Thailand (+66)',
			'228' => 'Togo (+228)',
			'676' => 'Tonga (+676)',
			'1868' => 'Trinidad & Tobago (+1868)',
			'216' => 'Tunisia (+216)',
			'90' => 'Turkey (+90)',
			'7' => 'Turkmenistan (+7)',
			'993' => 'Turkmenistan (+993)',
			'1649' => 'Turks & Caicos Islands (+1649)',
			'688' => 'Tuvalu (+688)',
			'256' => 'Uganda (+256)',
			'380' => 'Ukraine (+380)',
			'971' => 'United Arab Emirates (+971)',
			'598' => 'Uruguay (+598)',
			'7' => 'Uzbekistan (+7)',
			'678' => 'Vanuatu (+678)',
			'379' => 'Vatican City (+379)',
			'58' => 'Venezuela (+58)',
			'84' => 'Vietnam (+84)',
			'84' => 'Virgin Islands - British (+1284)',
			'84' => 'Virgin Islands - US (+1340)',
			'681' => 'Wallis & Futuna (+681)',
			'969' => 'Yemen (North)(+969)',
			'967' => 'Yemen (South)(+967)',
			'260' => 'Zambia (+260)',
			'263' => 'Zimbabwe (+263)',
		];

		return $array;
	}

	function getCities() {
		$array = [
			'Abu Dhabi' => [
				"Abu Dhabi Gate City",
				"Abu Dhabi Hills",
				"Abu Dhabi International Airport",
				"Al Adla ",
				"Al Aman", "Al Bahya", "Al Bandar (Al Raha)", "Al Dafrah", "Al Etihad", "Al Falah City",
				"Al Forsan Village (Khalifa- A)", "Al Gurum Resort", "Al Hosn", "Al Karamah", "Al Khalidiyah",
				"Al Khubeirah", "Al Mafraq", "Al Manhal", "Al Maqta", "Al Markaziyah", "Al Markaziyah West",
				"Al Maryah Island", "Al Mina", "Al Muneera (Al Raha)", "Al Muntazah", "Al Musalla", "Al Mushrif",
				"Al Muzoon", "Al Nahyan", "Al Raha", "Al Raha Beach", "Al Rahba", "Al Ras Al Akhdar",
				"Al Rayyana (Khalifa- A)", "Al Reef", "Al Rowdah", "Al Ruwais (Western Region)", "Al Sader", "Al Safarrat",
				"Al Samha", "Al Shaleela", "Al Shamkha", "Al Shamkha South", "Al Shawamekh", "Al Wahdah", "Al Wathba ",
				"Al Zaab", "Al Zafranah", "Al Zahraa", "Al Zeina (Al Raha)", "Bani Yas East", "Bani Yas West", "BreakWater",
				"Capital Centre", "Golf Gardens (Khalifa- A)", "Hydra Village (Shahama)", "Khor Al Bateen",
				"Madinat Khalifa - A", "Madinat Khalifa - C", "Madinat Zayed", "Mahwi", "Masdar City",
				"Mohammed Bin Zayed City", "Mussafah Industrial City", "Mussafah South", "New Shahama", "Old Bahya",
				"Port Zayed (Al Mina)", "Qasr El Bahr", "Qasr El Shatie", "Reem Island", "Saadiyat Island",
				"Sas Al Nakheel (Khalifa- A)", "Sas Al Nakhl Island", "Shahama", "Shakhbout City",
				"Tourist Club Area (Al Zahiya)", "Western Region", "Yas Island", "Zayed Sports City",
			],
			'Ajman' => [
				"Ajman City Center", "Ajman Corniche", "Ajman Free Zone", "Ajman Industrial Area 1 ",
				"Ajman Industrial Area 2 ", "Ajman Pearl", "Ajman University", "Al Alia", "Al Bustan", "Al Butain",
				"Al Hamidiya", "Al Hamidiya 1", "Al Hamidiya 2", "Al Helio", "Al Heliow 1", "Al Heliow 2", "Al Jurf 1",
				"Al Jurf 2", "Al Jurf Industrial Area 1", "Al Jurf Industrial Area 2", "Al Jurf Industrial Area 3",
				"Al Muntazi 1", "Al Muntazi 2", "Al Mushairef", "Al Mwaihat 1", "Al Mwaihat 2", "Al Mwaihat 3", "Al Nakhil",
				"Al Nakhil 1", "Al Nakhil 2", "Al Nuaimia 1", "Al Nuaimia 2", "Al Raqaib 1", "Al Raqaib 2", "Al Rashidiya 1",
				"Al Rashidiya 2", "Al Rashidiya 3", "Al Rawda 1 Al Zahraa", "Al Rawda 2 Al Zahraa", "Al Rawda 3 Al Zahraa",
				"Al Rumailah", "Al Tallah 1", "Al Tallah 2", "Al Yasmeen", "Al Zahya", "Al Zawarah", "Al Zora",
				"Emirates City", "Garden City", "Ittihad Village",
			],
			'Al Ain' => [
				"Abu Samrah", "Al Agabiyya", "Al Ain International Airport", "Al Ain Zoo", "Al Ameriya", "Al Bateen",
				"Al Dhahir", "Al Foaa", "Al Hili", "Al Jahili", "Al Jimi", "Al Khabisi", "Al Kuwaitat", "Al Manasir",
				"Al Maqam", "Al Marakhaniya", "Al Masoudi", "Al Murabaa", "Al Muraijeb", "Al Mutarad", "Al Mutawaa",
				"Al Muwaiji", "Al Nabagh", "Al Neyadat", "Al Qattara", "Al Sad", "Al Salamat District", "Al Sarooj",
				"Al Towayya", "Al Yahar", "Alain Al Fiyada", "Asharej", "Bedda Bn Ammar", "Falaj Hazzaa",
				"Industrial Area", "Khatim Al Shikla", "Mezyed", "Mubzara", "Neima", "Remah", "Tawam", "UAE University",
				"Um Ghaffa", "Zakher",
			],
			'Dubai' => [
				"Abu Hail", "Academic City", "Al Awir", "Al Bada'a", "Al Baraha", "Al Barari", "Al Barsha 1",
				"Al Barsha 2", "Al Barsha 3", "Al Barsha South", "Al Dhagaya", "Al Furjan", "Al Garhoud", "Al Hamriya",
				"Al Hudaiba", "Al Jaddaf", "Al Jaffiliya", "Al Karama", "Al Khabaisi", "Al Khawaneej 1", "Al Khawaneej 2",
				"Al Mamzar", "Al Manara", "Al Mankhool", "Al Mina", "Al Mizhar 1", "Al Mizhar 2", "Al Muraqqabat",
				"Al Murar", "Al Mushrif", "Al Muteena", "Al Nahda 1", "Al Nahda 2", "Al Quoz 1", "Al Quoz 2",
				"Al Quoz 3", "Al Quoz 4", "Al Quoz Industrial Area 1", "Al Quoz Industrial Area 2",
				"Al Quoz Industrial Area 3", "Al Quoz Industrial Area 4", "Al Qusais 1", "Al Qusais 2", "Al Qusais 3",
				"Al Qusais Industrial Area 1", "Al Qusais Industrial Area 2", "Al Qusais Industrial Area 3",
				"Al Qusais Industrial Area 4", "Al Qusais Industrial Area 5", "Al Raffa", "Al Ras", "Al Rashidiya",
				"Al Rigga", "Al Sabkha", "Al Safa", "Al Safa 2", "Al Satwa", "Al Shindagha", "Al Souq Al Kabeer",
				"Al Sufouh 1", "Al Sufouh 2", "Al Twar 1", "Al Twar 2", "Al Twar 3", "Al Waheda", "Al Warqa 1",
				"Al Warqa 2", "Al Warqa 3", "Al Warqa 4", "Al Warqa 5", "Al Wasl", "Arabian Ranches", "Arabian Ranches 2",
				"Arjan", "Barsha Heights - TECOM", "Bukadra", "Business Bay", "Corniche Deira", "DIFC", "Discovery Gardens",
				"Downtown Burj Khalifa", "Downtown Jabel Ali", "Dubai Airport Freezone", "Dubai Cargo Village",
				"Dubai Design District", "Dubai Falcon City", "Dubai Festival City", "Dubai Healthcare City", "Dubai Hills",
				"Dubai International Airport", "Dubai Internet City - DIC", "Dubai Investments Park 1",
				"Dubai Investments Park 2", "Dubai Lifestyle City", "Dubai Marina", "Dubai Maritime City",
				"Dubai Media City", "Dubai Motor City", "Dubai Silicon Oasis", "Dubai Sports City", "Dubai Studio City",
				"Dubai Techno Park", "Dubai World Central - DWC", "Dubai World Trade Center - DWTC", "Emirates Hills",
				"Gardens", "Global Village", "Green Community", "Green Community Motor City", "Hatta", "Hor Al Anz",
				"Hor Al Anz East", "Ibn Batutta Mall", "IMPZ", "International City", "International City 2", "Jebel Ali 1",
				"Jebel Ali 2", "Jebel Ali Freezone", "Jebel Ali Freezone Extension", "Jebel Ali Industrial Area",
				"Jumeirah 1", "Jumeirah 2", "Jumeirah 3", "Jumeirah Beach Residence - JBR", "Jumeirah Golf Estates",
				"Jumeirah Heights", "Jumeirah Islands", "Jumeirah Lakes Towers - JLT", "Jumeirah Park",
				"Jumeirah Village Circle - JVC", "Jumeirah Village Triangle - JVT", "Knowledge Village", "Layan Community",
				"Legends", "Liwan", "Majan", "MBR- Al Merkad", "Meadows", "Meydan South", "Mira Community", "Mirdif",
				"Mudon", "Muhaisnah 1", "Muhaisnah 2", "Muhaisnah 3", "Muhaisnah 4", "Nad Al Sheba 1", "Nad Al Sheba 2",
				"Nad Al Sheba 3", "Nad Al Sheba 4", "Nadd Al Hamar", "Nadd Al Shamma", "Naif", "Oud Al Muteena",
				"Oud Metha", "Port Rashid", "Port Saeed", "Ras Al Khor", "Ras Al Khor Indsutrial Area 1",
				"Ras Al Khor Indsutrial Area 2", "Ras Al Khor Indsutrial Area 3", "Remraam", "Rigga Al Buteen", "Springs",
				"The Greens", "The Lakes", "The Palm Deira", "The Palm Jebel Ali", "The Palm Jumeirah", "The Skycourts",
				"The Sustainable City", "The Villa", "Um Al Sheif", "Umm Hurair 1", "Umm Hurair 2", "Umm Ramool",
				"Umm Suqeim 1", "Umm Suqeim 2", "Umm Suqeim 3", "Wadi Alamardi", "Warsan 1", "Warsan 2", "Waterfront",
				"Za'abeel 1", "Za'abeel 2",
			],
			'Fujairah' => [
				"Al Aqah", "Al Bedia ", "Al Buthna ", "Al Farfar", "Al Faseel", "Al Gurfa", "Al Hala ", "Al Haray",
				"Al Heel ", "Al Ittihad", "Al Mahatta", "Al Owaid", "Al Qurayya", "Al Taween", "Albeledah", "Anajaimat",
				"Awhala ", "Dedna", "Dibba", "Dibba Al Hisn", "Dibba Industrial Area", "Fujairah Free Trade Zone",
				"Fujairah Intl Airport", "Fujairah Port", "Halefaath", "Industrial Area", "Kalba", "Karsha", "Khor Fakkan",
				"Madhab", "Masafi", "Merashid", "Mirbah", "Old Fujairah City", "Qidfa", "Rughaylat", "Rumailah",
				"Sakamkam", "Sharm ", "Suwayfah", "Zubara",
			],
			'Ras Al Khaimah' => [
				"Al Darbijaniyah", "Al Dhait North", "Al Dhait South", "Al Duhaisah", "Al Fahlain", "Al Ghubb",
				"Al Hamra Free Zone", "Al Hamra Industrial Area", "Al Hamra Island", "Al Hamra Village", "Al Hudaibah",
				"Al Jazeerah Al Hamra", "Al Jesser Area", "Al Juwais Area", "Al Kharran", "Al Mairid", "Al Marjan Island",
				"Al Mataf", "Al Nadiyah", "Al Nakheel Area", "Al Nudood", "Al Qurm", "Al Qusaidat", "Al Ragibah",
				"Al Sall", "Al Seer", "Al Soor", "Al Turfah", "Al Uraibi", "Al Zahra", "Burairaat", "Dafan Al Khor",
				"Dafan Al Nakheel", "Dahan", "Digdagga", "Ghalilah", "Hamrania", "Khatt", "Khazam", "Liwa Badr", "Mamoora",
				"Mina Al arab", "RAK City", "Rams", "Ras Al Selaab Area", "Refa`ah", "Seih Al Ghubb", "Seih al Harf",
				"Seih Al Hudaibah", "Seih Al Qusaidat", "Seih Al Uraibi", "Seih Shihyar", "Shamal Haqueel",
				"Shamal Julphar", "Shareesha", "Sidroh", "Suhaim Area", "Wadi Ammar",
			],
			'Sharjah' => [
				"Abu Shagara", "Al  Muntazah", "Al Abar", "Al Atain", "Al Azra", "Al Bataeh", "Al Bdai'a Subrub",
				"Al Darari", "Al Dhaid", "Al Elyash", "Al Falah Suburb", "Al Falaj", "Al Fayha", "Al Fisht", "Al Ghaphia",
				"Al Gharayen", "Al Ghubaiba", "Al Ghuwair", "Al Goaz", "Al Hazana", "Al Homaa", "Al Jazzat", "Al Jubail",
				"Al Juraina", "Al Khaledia Suburb", "Al Khan", "Al Khezamia", "Al Layyah", "Al Mahatta", "Al Majaz 1",
				"Al Majaz 2", "Al Majaz 3", "Al Mamzar", "Al Manakh", "Al Manazel", "Al Mansura", "Al Mareija", "Al Mirgab",
				"Al Mujarah", "Al Musalla", "Al Nabba", "Al Nad", "Al Nahda", "Al Nasserya", "Al Nekhailat", "Al Noof",
				"Al Qadisia", "Al Qasimia", "Al Qulayaa", "Al Rahmania", "Al Ramaqia", "Al Ramla East", "Al Ramla West",
				"Al Ramtha", "Al Rifah", "Al Riffa", "Al Sabkha", "Al Seef", "Al Seyouh", "Al Shahba", "Al Shuwaihen",
				"Al Soor", "Al Sweihat", "Al Taawun", "Al Talaa", "Al Tarfa", "Al Yarmook", "Barashi", "Bu Danig",
				"Bu Tina", "Dasman", "Industrial Area 1", "Industrial Area 10", "Industrial Area 11", "Industrial Area 12",
				"Industrial Area 13", "Industrial Area 15", "Industrial Area 17", "Industrial Area 18", "Industrial Area 2",
				"Industrial Area 3", "Industrial Area 4", "Industrial Area 5", "Industrial Area 6", "Industrial Area 7",
				"Industrial Area 8", "Industrial Area 9", "Maysaloon", "Muwafjah", "Muwaileh Commercial", "Muzairah",
				"Rolla", "Saif Zone", "Samnan", "Sharqan", "Um Altaraffa", "University of Sharjah",
			],
			'Um Al Quwain' => [
				"Al Aahad", "Al Abrab", "Al Dar Al Baidah", "Al Haditha", "Al Hawiyah", "Al Hobob", "Al Humrah - A",
				"Al Humrah - B", "Al Humrah - C", "Al Humrah - D", "Al Khor", "Al Limgadhar", "Al Maidan", "Al Qarain",
				"Al Raas - A", "Al Raas - B", "Al Raas - C", "Al Rafaah", "Al Ramlah", "Al Raudah", "Al Riqqah",
				"Al Salamah - A", "Al Salamah - B", "Al Salamah - C", "Defence Camp", "Emirates Modern Industrial",
				"Green Belt", "Industrial Area", "Khalifa City", "Latin", "Mohamed Bin Rashed", "Old Town Area",
				"Umm Al Quwain Airport", "Umm Al Quwain Marina",
			]
		];
		$cities = [];
		foreach ($array as $i => $a) {
			array_push($cities, $i);
		}
		return $cities;
	}

	function getCountries() {
		return [
			"Afghanistan",
			"Albania",
			"Algeria",
			"American Samoa",
			"Andorra",
			"Angola",
			"Anguilla",
			"Antarctica",
			"Antigua and Barbuda",
			"Argentina",
			"Armenia",
			"Aruba",
			"Australia",
			"Austria",
			"Azerbaijan",
			"Bahamas (the)",
			"Bahrain",
			"Bangladesh",
			"Barbados",
			"Belarus",
			"Belgium",
			"Belize",
			"Benin",
			"Bermuda",
			"Bhutan",
			"Bolivia (Plurinational State of)",
			"Bonaire, Sint Eustatius and Saba",
			"Bosnia and Herzegovina",
			"Botswana",
			"Bouvet Island",
			"Brazil",
			"British Indian Ocean Territory (the)",
			"Brunei Darussalam",
			"Bulgaria",
			"Burkina Faso",
			"Burundi",
			"Cabo Verde",
			"Cambodia",
			"Cameroon",
			"Canada",
			"Cayman Islands (the)",
			"Central African Republic (the)",
			"Chad",
			"Chile",
			"China",
			"Christmas Island",
			"Cocos (Keeling) Islands (the)",
			"Colombia",
			"Comoros (the)",
			"Congo (the Democratic Republic of the)",
			"Congo (the)",
			"Cook Islands (the)",
			"Costa Rica",
			"Croatia",
			"Cuba",
			"Curaçao",
			"Cyprus",
			"Czechia",
			"Côte d'Ivoire",
			"Denmark",
			"Djibouti",
			"Dominica",
			"Dominican Republic (the)",
			"Ecuador",
			"Egypt",
			"El Salvador",
			"Equatorial Guinea",
			"Eritrea",
			"Estonia",
			"Eswatini",
			"Ethiopia",
			"Falkland Islands (the) [Malvinas]",
			"Faroe Islands (the)",
			"Fiji",
			"Finland",
			"France",
			"French Guiana",
			"French Polynesia",
			"French Southern Territories (the)",
			"Gabon",
			"Gambia (the)",
			"Georgia",
			"Germany",
			"Ghana",
			"Gibraltar",
			"Greece",
			"Greenland",
			"Grenada",
			"Guadeloupe",
			"Guam",
			"Guatemala",
			"Guernsey",
			"Guinea",
			"Guinea-Bissau",
			"Guyana",
			"Haiti",
			"Heard Island and McDonald Islands",
			"Holy See (the)",
			"Honduras",
			"Hong Kong",
			"Hungary",
			"Iceland",
			"India",
			"Indonesia",
			"Iran (Islamic Republic of)",
			"Iraq",
			"Ireland",
			"Isle of Man",
			"Israel",
			"Italy",
			"Jamaica",
			"Japan",
			"Jersey",
			"Jordan",
			"Kazakhstan",
			"Kenya",
			"Kiribati",
			"Korea (the Democratic People's Republic of)",
			"Korea (the Republic of)",
			"Kuwait",
			"Kyrgyzstan",
			"Lao People's Democratic Republic (the)",
			"Latvia",
			"Lebanon",
			"Lesotho",
			"Liberia",
			"Libya",
			"Liechtenstein",
			"Lithuania",
			"Luxembourg",
			"Macao",
			"Madagascar",
			"Malawi",
			"Malaysia",
			"Maldives",
			"Mali",
			"Malta",
			"Marshall Islands (the)",
			"Martinique",
			"Mauritania",
			"Mauritius",
			"Mayotte",
			"Mexico",
			"Micronesia (Federated States of)",
			"Moldova (the Republic of)",
			"Monaco",
			"Mongolia",
			"Montenegro",
			"Montserrat",
			"Morocco",
			"Mozambique",
			"Myanmar",
			"Namibia",
			"Nauru",
			"Nepal",
			"Netherlands (the)",
			"New Caledonia",
			"New Zealand",
			"Nicaragua",
			"Niger (the)",
			"Nigeria",
			"Niue",
			"Norfolk Island",
			"Northern Mariana Islands (the)",
			"Norway",
			"Oman",
			"Pakistan",
			"Palau",
			"Palestine, State of",
			"Panama",
			"Papua New Guinea",
			"Paraguay",
			"Peru",
			"Philippines (the)",
			"Pitcairn",
			"Poland",
			"Portugal",
			"Puerto Rico",
			"Qatar",
			"Republic of North Macedonia",
			"Romania",
			"Russian Federation (the)",
			"Rwanda",
			"Réunion",
			"Saint Barthélemy",
			"Saint Helena, Ascension and Tristan da Cunha",
			"Saint Kitts and Nevis",
			"Saint Lucia",
			"Saint Martin (French part)",
			"Saint Pierre and Miquelon",
			"Saint Vincent and the Grenadines",
			"Samoa",
			"San Marino",
			"Sao Tome and Principe",
			"Saudi Arabia",
			"Senegal",
			"Serbia",
			"Seychelles",
			"Sierra Leone",
			"Singapore",
			"Sint Maarten (Dutch part)",
			"Slovakia",
			"Slovenia",
			"Solomon Islands",
			"Somalia",
			"South Africa",
			"South Georgia and the South Sandwich Islands",
			"South Sudan",
			"Spain",
			"Sri Lanka",
			"Sudan (the)",
			"Suriname",
			"Svalbard and Jan Mayen",
			"Sweden",
			"Switzerland",
			"Syrian Arab Republic",
			"Taiwan",
			"Tajikistan",
			"Tanzania, United Republic of",
			"Thailand",
			"Timor-Leste",
			"Togo",
			"Tokelau",
			"Tonga",
			"Trinidad and Tobago",
			"Tunisia",
			"Turkey",
			"Turkmenistan",
			"Turks and Caicos Islands (the)",
			"Tuvalu",
			"Uganda",
			"Ukraine",
			"United Arab Emirates (the)",
			"United Kingdom of Great Britain and Northern Ireland (the)",
			"United States Minor Outlying Islands (the)",
			"United States of America (the)",
			"Uruguay",
			"Uzbekistan",
			"Vanuatu",
			"Venezuela (Bolivarian Republic of)",
			"Viet Nam",
			"Virgin Islands (British)",
			"Virgin Islands (U.S.)",
			"Wallis and Futuna",
			"Western Sahara",
			"Yemen",
			"Zambia",
			"Zimbabwe",
			"Åland Islands"
		];
	}

	function getLanguages() {
		return array(
			'af' => 'Afrikaans',
			'sq' => 'Albanian - shqip',
			'am' => 'Amharic - አማርኛ',
			'ar' => 'Arabic - العربية',
			'an' => 'Aragonese - aragonés',
			'hy' => 'Armenian - հայերեն',
			'ast' => 'Asturian - asturianu',
			'az' => 'Azerbaijani - azərbaycan dili',
			'eu' => 'Basque - euskara',
			'be' => 'Belarusian - беларуская',
			'bn' => 'Bengali - বাংলা',
			'bs' => 'Bosnian - bosanski',
			'br' => 'Breton - brezhoneg',
			'bg' => 'Bulgarian - български',
			'ca' => 'Catalan - català',
			'ckb' => 'Central Kurdish - کوردی (دەستنوسی عەرەبی)',
			'zh' => 'Chinese - 中文',
			'zh-HK' => 'Chinese (Hong Kong) - 中文（香港）',
			'zh-CN' => 'Chinese (Simplified) - 中文（简体）',
			'zh-TW' => 'Chinese (Traditional) - 中文（繁體）',
			'co' => 'Corsican',
			'hr' => 'Croatian - hrvatski',
			'cs' => 'Czech - čeština',
			'da' => 'Danish - dansk',
			'nl' => 'Dutch - Nederlands',
			'en' => 'English',
			'en-AU' => 'English (Australia)',
			'en-CA' => 'English (Canada)',
			'en-IN' => 'English (India)',
			'en-NZ' => 'English (New Zealand)',
			'en-ZA' => 'English (South Africa)',
			'en-GB' => 'English (United Kingdom)',
			'en-US' => 'English (United States)',
			'eo' => 'Esperanto - esperanto',
			'et' => 'Estonian - eesti',
			'fo' => 'Faroese - føroyskt',
			'fil' => 'Filipino',
			'fi' => 'Finnish - suomi',
			'fr' => 'French - français',
			'fr-CA' => 'French (Canada) - français (Canada)',
			'fr-FR' => 'French (France) - français (France)',
			'fr-CH' => 'French (Switzerland) - français (Suisse)',
			'gl' => 'Galician - galego',
			'ka' => 'Georgian - ქართული',
			'de' => 'German - Deutsch',
			'de-AT' => 'German (Austria) - Deutsch (Österreich)',
			'de-DE' => 'German (Germany) - Deutsch (Deutschland)',
			'de-LI' => 'German (Liechtenstein) - Deutsch (Liechtenstein)',
			'de-CH' => 'German (Switzerland) - Deutsch (Schweiz)',
			'el' => 'Greek - Ελληνικά',
			'gn' => 'Guarani',
			'gu' => 'Gujarati - ગુજરાતી',
			'ha' => 'Hausa',
			'haw' => 'Hawaiian - ʻŌlelo Hawaiʻi',
			'he' => 'Hebrew - עברית',
			'hi' => 'Hindi - हिन्दी',
			'hu' => 'Hungarian - magyar',
			'is' => 'Icelandic - íslenska',
			'id' => 'Indonesian - Indonesia',
			'ia' => 'Interlingua',
			'ga' => 'Irish - Gaeilge',
			'it' => 'Italian - italiano',
			'it-IT' => 'Italian (Italy) - italiano (Italia)',
			'it-CH' => 'Italian (Switzerland) - italiano (Svizzera)',
			'ja' => 'Japanese - 日本語',
			'kn' => 'Kannada - ಕನ್ನಡ',
			'kk' => 'Kazakh - қазақ тілі',
			'km' => 'Khmer - ខ្មែរ',
			'ko' => 'Korean - 한국어',
			'ku' => 'Kurdish - Kurdî',
			'ky' => 'Kyrgyz - кыргызча',
			'lo' => 'Lao - ລາວ',
			'la' => 'Latin',
			'lv' => 'Latvian - latviešu',
			'ln' => 'Lingala - lingála',
			'lt' => 'Lithuanian - lietuvių',
			'mk' => 'Macedonian - македонски',
			'ms' => 'Malay - Bahasa Melayu',
			'ml' => 'Malayalam - മലയാളം',
			'mt' => 'Maltese - Malti',
			'mr' => 'Marathi - मराठी',
			'mn' => 'Mongolian - монгол',
			'ne' => 'Nepali - नेपाली',
			'no' => 'Norwegian - norsk',
			'nb' => 'Norwegian Bokmål - norsk bokmål',
			'nn' => 'Norwegian Nynorsk - nynorsk',
			'oc' => 'Occitan',
			'or' => 'Oriya - ଓଡ଼ିଆ',
			'om' => 'Oromo - Oromoo',
			'ps' => 'Pashto - پښتو',
			'fa' => 'Persian - فارسی',
			'pl' => 'Polish - polski',
			'pt' => 'Portuguese - português',
			'pt-BR' => 'Portuguese (Brazil) - português (Brasil)',
			'pt-PT' => 'Portuguese (Portugal) - português (Portugal)',
			'pa' => 'Punjabi - ਪੰਜਾਬੀ',
			'qu' => 'Quechua',
			'ro' => 'Romanian - română',
			'mo' => 'Romanian (Moldova) - română (Moldova)',
			'rm' => 'Romansh - rumantsch',
			'ru' => 'Russian - русский',
			'gd' => 'Scottish Gaelic',
			'sr' => 'Serbian - српски',
			'sh' => 'Serbo-Croatian - Srpskohrvatski',
			'sn' => 'Shona - chiShona',
			'sd' => 'Sindhi',
			'si' => 'Sinhala - සිංහල',
			'sk' => 'Slovak - slovenčina',
			'sl' => 'Slovenian - slovenščina',
			'so' => 'Somali - Soomaali',
			'st' => 'Southern Sotho',
			'es' => 'Spanish - español',
			'es-AR' => 'Spanish (Argentina) - español (Argentina)',
			'es-419' => 'Spanish (Latin America) - español (Latinoamérica)',
			'es-MX' => 'Spanish (Mexico) - español (México)',
			'es-ES' => 'Spanish (Spain) - español (España)',
			'es-US' => 'Spanish (United States) - español (Estados Unidos)',
			'su' => 'Sundanese',
			'sw' => 'Swahili - Kiswahili',
			'sv' => 'Swedish - svenska',
			'tg' => 'Tajik - тоҷикӣ',
			'ta' => 'Tamil - தமிழ்',
			'tt' => 'Tatar',
			'te' => 'Telugu - తెలుగు',
			'th' => 'Thai - ไทย',
			'ti' => 'Tigrinya - ትግርኛ',
			'to' => 'Tongan - lea fakatonga',
			'tr' => 'Turkish - Türkçe',
			'tk' => 'Turkmen',
			'tw' => 'Twi',
			'uk' => 'Ukrainian - українська',
			'ur' => 'Urdu - اردو',
			'ug' => 'Uyghur',
			'uz' => 'Uzbek - o‘zbek',
			'vi' => 'Vietnamese - Tiếng Việt',
			'wa' => 'Walloon - wa',
			'cy' => 'Welsh - Cymraeg',
			'fy' => 'Western Frisian',
			'xh' => 'Xhosa',
			'yi' => 'Yiddish',
			'yo' => 'Yoruba - Èdè Yorùbá',
			'zu' => 'Zulu - isiZulu'
		);
	}

	function getAreas($city) {
		$array = array(
			'Abu Dhabi' => array(
				"Abu Dhabi Gate City",
				"Abu Dhabi Hills",
				"Abu Dhabi International Airport",
				"Al Adla ",
				"Al Aman", "Al Bahya", "Al Bandar (Al Raha)", "Al Dafrah", "Al Etihad", "Al Falah City",
				"Al Forsan Village (Khalifa- A)", "Al Gurum Resort", "Al Hosn", "Al Karamah", "Al Khalidiyah",
				"Al Khubeirah", "Al Mafraq", "Al Manhal", "Al Maqta", "Al Markaziyah", "Al Markaziyah West",
				"Al Maryah Island", "Al Mina", "Al Muneera (Al Raha)", "Al Muntazah", "Al Musalla", "Al Mushrif",
				"Al Muzoon", "Al Nahyan", "Al Raha", "Al Raha Beach", "Al Rahba", "Al Ras Al Akhdar",
				"Al Rayyana (Khalifa- A)", "Al Reef", "Al Rowdah", "Al Ruwais (Western Region)", "Al Sader", "Al Safarrat",
				"Al Samha", "Al Shaleela", "Al Shamkha", "Al Shamkha South", "Al Shawamekh", "Al Wahdah", "Al Wathba ",
				"Al Zaab", "Al Zafranah", "Al Zahraa", "Al Zeina (Al Raha)", "Bani Yas East", "Bani Yas West", "BreakWater",
				"Capital Centre", "Golf Gardens (Khalifa- A)", "Hydra Village (Shahama)", "Khor Al Bateen",
				"Madinat Khalifa - A", "Madinat Khalifa - C", "Madinat Zayed", "Mahwi", "Masdar City",
				"Mohammed Bin Zayed City", "Mussafah Industrial City", "Mussafah South", "New Shahama", "Old Bahya",
				"Port Zayed (Al Mina)", "Qasr El Bahr", "Qasr El Shatie", "Reem Island", "Saadiyat Island",
				"Sas Al Nakheel (Khalifa- A)", "Sas Al Nakhl Island", "Shahama", "Shakhbout City",
				"Tourist Club Area (Al Zahiya)", "Western Region", "Yas Island", "Zayed Sports City",
			),
			'Ajman' => array(
				"Ajman City Center", "Ajman Corniche", "Ajman Free Zone", "Ajman Industrial Area 1 ",
				"Ajman Industrial Area 2 ", "Ajman Pearl", "Ajman University", "Al Alia", "Al Bustan", "Al Butain",
				"Al Hamidiya", "Al Hamidiya 1", "Al Hamidiya 2", "Al Helio", "Al Heliow 1", "Al Heliow 2", "Al Jurf 1",
				"Al Jurf 2", "Al Jurf Industrial Area 1", "Al Jurf Industrial Area 2", "Al Jurf Industrial Area 3",
				"Al Muntazi 1", "Al Muntazi 2", "Al Mushairef", "Al Mwaihat 1", "Al Mwaihat 2", "Al Mwaihat 3", "Al Nakhil",
				"Al Nakhil 1", "Al Nakhil 2", "Al Nuaimia 1", "Al Nuaimia 2", "Al Raqaib 1", "Al Raqaib 2", "Al Rashidiya 1",
				"Al Rashidiya 2", "Al Rashidiya 3", "Al Rawda 1 Al Zahraa", "Al Rawda 2 Al Zahraa", "Al Rawda 3 Al Zahraa",
				"Al Rumailah", "Al Tallah 1", "Al Tallah 2", "Al Yasmeen", "Al Zahya", "Al Zawarah", "Al Zora",
				"Emirates City", "Garden City", "Ittihad Village",
			),
			'Al Ain' => array(
				"Abu Samrah", "Al Agabiyya", "Al Ain International Airport", "Al Ain Zoo", "Al Ameriya", "Al Bateen",
				"Al Dhahir", "Al Foaa", "Al Hili", "Al Jahili", "Al Jimi", "Al Khabisi", "Al Kuwaitat", "Al Manasir",
				"Al Maqam", "Al Marakhaniya", "Al Masoudi", "Al Murabaa", "Al Muraijeb", "Al Mutarad", "Al Mutawaa",
				"Al Muwaiji", "Al Nabagh", "Al Neyadat", "Al Qattara", "Al Sad", "Al Salamat District", "Al Sarooj",
				"Al Towayya", "Al Yahar", "Alain Al Fiyada", "Asharej", "Bedda Bn Ammar", "Falaj Hazzaa",
				"Industrial Area", "Khatim Al Shikla", "Mezyed", "Mubzara", "Neima", "Remah", "Tawam", "UAE University",
				"Um Ghaffa", "Zakher",
			),
			'Dubai' => array(
				"Abu Hail", "Academic City", "Al Awir", "Al Bada'a", "Al Baraha", "Al Barari", "Al Barsha 1",
				"Al Barsha 2", "Al Barsha 3", "Al Barsha South", "Al Dhagaya", "Al Furjan", "Al Garhoud", "Al Hamriya",
				"Al Hudaiba", "Al Jaddaf", "Al Jaffiliya", "Al Karama", "Al Khabaisi", "Al Khawaneej 1", "Al Khawaneej 2",
				"Al Mamzar", "Al Manara", "Al Mankhool", "Al Mina", "Al Mizhar 1", "Al Mizhar 2", "Al Muraqqabat",
				"Al Murar", "Al Mushrif", "Al Muteena", "Al Nahda 1", "Al Nahda 2", "Al Quoz 1", "Al Quoz 2",
				"Al Quoz 3", "Al Quoz 4", "Al Quoz Industrial Area 1", "Al Quoz Industrial Area 2",
				"Al Quoz Industrial Area 3", "Al Quoz Industrial Area 4", "Al Qusais 1", "Al Qusais 2", "Al Qusais 3",
				"Al Qusais Industrial Area 1", "Al Qusais Industrial Area 2", "Al Qusais Industrial Area 3",
				"Al Qusais Industrial Area 4", "Al Qusais Industrial Area 5", "Al Raffa", "Al Ras", "Al Rashidiya",
				"Al Rigga", "Al Sabkha", "Al Safa", "Al Safa 2", "Al Satwa", "Al Shindagha", "Al Souq Al Kabeer",
				"Al Sufouh 1", "Al Sufouh 2", "Al Twar 1", "Al Twar 2", "Al Twar 3", "Al Waheda", "Al Warqa 1",
				"Al Warqa 2", "Al Warqa 3", "Al Warqa 4", "Al Warqa 5", "Al Wasl", "Arabian Ranches", "Arabian Ranches 2",
				"Arjan", "Barsha Heights - TECOM", "Bukadra", "Business Bay", "Corniche Deira", "DIFC", "Discovery Gardens",
				"Downtown Burj Khalifa", "Downtown Jabel Ali", "Dubai Airport Freezone", "Dubai Cargo Village",
				"Dubai Design District", "Dubai Falcon City", "Dubai Festival City", "Dubai Healthcare City", "Dubai Hills",
				"Dubai International Airport", "Dubai Internet City - DIC", "Dubai Investments Park 1",
				"Dubai Investments Park 2", "Dubai Lifestyle City", "Dubai Marina", "Dubai Maritime City",
				"Dubai Media City", "Dubai Motor City", "Dubai Silicon Oasis", "Dubai Sports City", "Dubai Studio City",
				"Dubai Techno Park", "Dubai World Central - DWC", "Dubai World Trade Center - DWTC", "Emirates Hills",
				"Gardens", "Global Village", "Green Community", "Green Community Motor City", "Hatta", "Hor Al Anz",
				"Hor Al Anz East", "Ibn Batutta Mall", "IMPZ", "International City", "International City 2", "Jebel Ali 1",
				"Jebel Ali 2", "Jebel Ali Freezone", "Jebel Ali Freezone Extension", "Jebel Ali Industrial Area",
				"Jumeirah 1", "Jumeirah 2", "Jumeirah 3", "Jumeirah Beach Residence - JBR", "Jumeirah Golf Estates",
				"Jumeirah Heights", "Jumeirah Islands", "Jumeirah Lakes Towers - JLT", "Jumeirah Park",
				"Jumeirah Village Circle - JVC", "Jumeirah Village Triangle - JVT", "Knowledge Village", "Layan Community",
				"Legends", "Liwan", "Majan", "MBR- Al Merkad", "Meadows", "Meydan South", "Mira Community", "Mirdif",
				"Mudon", "Muhaisnah 1", "Muhaisnah 2", "Muhaisnah 3", "Muhaisnah 4", "Nad Al Sheba 1", "Nad Al Sheba 2",
				"Nad Al Sheba 3", "Nad Al Sheba 4", "Nadd Al Hamar", "Nadd Al Shamma", "Naif", "Oud Al Muteena",
				"Oud Metha", "Port Rashid", "Port Saeed", "Ras Al Khor", "Ras Al Khor Indsutrial Area 1",
				"Ras Al Khor Indsutrial Area 2", "Ras Al Khor Indsutrial Area 3", "Remraam", "Rigga Al Buteen", "Springs",
				"The Greens", "The Lakes", "The Palm Deira", "The Palm Jebel Ali", "The Palm Jumeirah", "The Skycourts",
				"The Sustainable City", "The Villa", "Um Al Sheif", "Umm Hurair 1", "Umm Hurair 2", "Umm Ramool",
				"Umm Suqeim 1", "Umm Suqeim 2", "Umm Suqeim 3", "Wadi Alamardi", "Warsan 1", "Warsan 2", "Waterfront",
				"Za'abeel 1", "Za'abeel 2",
			),
			'Fujairah' => array(
				"Al Aqah", "Al Bedia ", "Al Buthna ", "Al Farfar", "Al Faseel", "Al Gurfa", "Al Hala ", "Al Haray",
				"Al Heel ", "Al Ittihad", "Al Mahatta", "Al Owaid", "Al Qurayya", "Al Taween", "Albeledah", "Anajaimat",
				"Awhala ", "Dedna", "Dibba", "Dibba Al Hisn", "Dibba Industrial Area", "Fujairah Free Trade Zone",
				"Fujairah Intl Airport", "Fujairah Port", "Halefaath", "Industrial Area", "Kalba", "Karsha", "Khor Fakkan",
				"Madhab", "Masafi", "Merashid", "Mirbah", "Old Fujairah City", "Qidfa", "Rughaylat", "Rumailah",
				"Sakamkam", "Sharm ", "Suwayfah", "Zubara",
			),
			'Ras Al Khaimah' => array(
				"Al Darbijaniyah", "Al Dhait North", "Al Dhait South", "Al Duhaisah", "Al Fahlain", "Al Ghubb",
				"Al Hamra Free Zone", "Al Hamra Industrial Area", "Al Hamra Island", "Al Hamra Village", "Al Hudaibah",
				"Al Jazeerah Al Hamra", "Al Jesser Area", "Al Juwais Area", "Al Kharran", "Al Mairid", "Al Marjan Island",
				"Al Mataf", "Al Nadiyah", "Al Nakheel Area", "Al Nudood", "Al Qurm", "Al Qusaidat", "Al Ragibah",
				"Al Sall", "Al Seer", "Al Soor", "Al Turfah", "Al Uraibi", "Al Zahra", "Burairaat", "Dafan Al Khor",
				"Dafan Al Nakheel", "Dahan", "Digdagga", "Ghalilah", "Hamrania", "Khatt", "Khazam", "Liwa Badr", "Mamoora",
				"Mina Al arab", "RAK City", "Rams", "Ras Al Selaab Area", "Refa`ah", "Seih Al Ghubb", "Seih al Harf",
				"Seih Al Hudaibah", "Seih Al Qusaidat", "Seih Al Uraibi", "Seih Shihyar", "Shamal Haqueel",
				"Shamal Julphar", "Shareesha", "Sidroh", "Suhaim Area", "Wadi Ammar",
			),
			'Sharjah' => array(
				"Abu Shagara", "Al  Muntazah", "Al Abar", "Al Atain", "Al Azra", "Al Bataeh", "Al Bdai'a Subrub",
				"Al Darari", "Al Dhaid", "Al Elyash", "Al Falah Suburb", "Al Falaj", "Al Fayha", "Al Fisht", "Al Ghaphia",
				"Al Gharayen", "Al Ghubaiba", "Al Ghuwair", "Al Goaz", "Al Hazana", "Al Homaa", "Al Jazzat", "Al Jubail",
				"Al Juraina", "Al Khaledia Suburb", "Al Khan", "Al Khezamia", "Al Layyah", "Al Mahatta", "Al Majaz 1",
				"Al Majaz 2", "Al Majaz 3", "Al Mamzar", "Al Manakh", "Al Manazel", "Al Mansura", "Al Mareija", "Al Mirgab",
				"Al Mujarah", "Al Musalla", "Al Nabba", "Al Nad", "Al Nahda", "Al Nasserya", "Al Nekhailat", "Al Noof",
				"Al Qadisia", "Al Qasimia", "Al Qulayaa", "Al Rahmania", "Al Ramaqia", "Al Ramla East", "Al Ramla West",
				"Al Ramtha", "Al Rifah", "Al Riffa", "Al Sabkha", "Al Seef", "Al Seyouh", "Al Shahba", "Al Shuwaihen",
				"Al Soor", "Al Sweihat", "Al Taawun", "Al Talaa", "Al Tarfa", "Al Yarmook", "Barashi", "Bu Danig",
				"Bu Tina", "Dasman", "Industrial Area 1", "Industrial Area 10", "Industrial Area 11", "Industrial Area 12",
				"Industrial Area 13", "Industrial Area 15", "Industrial Area 17", "Industrial Area 18", "Industrial Area 2",
				"Industrial Area 3", "Industrial Area 4", "Industrial Area 5", "Industrial Area 6", "Industrial Area 7",
				"Industrial Area 8", "Industrial Area 9", "Maysaloon", "Muwafjah", "Muwaileh Commercial", "Muzairah",
				"Rolla", "Saif Zone", "Samnan", "Sharqan", "Um Altaraffa", "University of Sharjah",
			),
			'Um Al Quwain' => array(
				"Al Aahad", "Al Abrab", "Al Dar Al Baidah", "Al Haditha", "Al Hawiyah", "Al Hobob", "Al Humrah - A",
				"Al Humrah - B", "Al Humrah - C", "Al Humrah - D", "Al Khor", "Al Limgadhar", "Al Maidan", "Al Qarain",
				"Al Raas - A", "Al Raas - B", "Al Raas - C", "Al Rafaah", "Al Ramlah", "Al Raudah", "Al Riqqah",
				"Al Salamah - A", "Al Salamah - B", "Al Salamah - C", "Defence Camp", "Emirates Modern Industrial",
				"Green Belt", "Industrial Area", "Khalifa City", "Latin", "Mohamed Bin Rashed", "Old Town Area",
				"Umm Al Quwain Airport", "Umm Al Quwain Marina",
			)
		);
		$areas = [];
		foreach ($array as $i => $a) {
			if($i == $city) {
				$areas = $a;
				break;
			}
		}
		return $array[$city];
	}

	function getAreasByOrg($city, $org) {
		$results = \App\Models\Area::where([
			['organization_id', $org],
			['city', $city],
		])->get();

		$array = array();
		foreach ($results as $result) {
			array_push($array, $result->area);
		}

		return $array;
	}

  function getName(){
      return ["bangladesh"=>[
          "dhaka",
          "chittagong"
      ]

          ,"india"=>
           ["Dehli",
            "Kolkata"
           ]
          ,"pakistan"=>[
              "Lahor"
          ]

      ];
  }

  function getCity(){
      return [ 'Bangladesh'=>[
                    'Dhaka',
                    'Chittagong'
                ]];

  }

  function name(){
      return "Alex";
  }

//  if(!function_exists('Areas')){
//       function  Areas(){
//          return [
//              'Abu Dhabi' => [
//                  "Abu Dhabi Gate City",
//                  "Abu Dhabi Hills",
//                  "Abu Dhabi International Airport",
//                  "Al Adla ",
//                  "Al Aman", "Al Bahya", "Al Bandar (Al Raha)", "Al Dafrah", "Al Etihad", "Al Falah City",
//                  "Al Forsan Village (Khalifa- A)", "Al Gurum Resort", "Al Hosn", "Al Karamah", "Al Khalidiyah",
//                  "Al Khubeirah", "Al Mafraq", "Al Manhal", "Al Maqta", "Al Markaziyah", "Al Markaziyah West",
//                  "Al Maryah Island", "Al Mina", "Al Muneera (Al Raha)", "Al Muntazah", "Al Musalla", "Al Mushrif",
//                  "Al Muzoon", "Al Nahyan", "Al Raha", "Al Raha Beach", "Al Rahba", "Al Ras Al Akhdar",
//                  "Al Rayyana (Khalifa- A)", "Al Reef", "Al Rowdah", "Al Ruwais (Western Region)", "Al Sader", "Al Safarrat",
//                  "Al Samha", "Al Shaleela", "Al Shamkha", "Al Shamkha South", "Al Shawamekh", "Al Wahdah", "Al Wathba ",
//                  "Al Zaab", "Al Zafranah", "Al Zahraa", "Al Zeina (Al Raha)", "Bani Yas East", "Bani Yas West", "BreakWater",
//                  "Capital Centre", "Golf Gardens (Khalifa- A)", "Hydra Village (Shahama)", "Khor Al Bateen",
//                  "Madinat Khalifa - A", "Madinat Khalifa - C", "Madinat Zayed", "Mahwi", "Masdar City",
//                  "Mohammed Bin Zayed City", "Mussafah Industrial City", "Mussafah South", "New Shahama", "Old Bahya",
//                  "Port Zayed (Al Mina)", "Qasr El Bahr", "Qasr El Shatie", "Reem Island", "Saadiyat Island",
//                  "Sas Al Nakheel (Khalifa- A)", "Sas Al Nakhl Island", "Shahama", "Shakhbout City",
//                  "Tourist Club Area (Al Zahiya)", "Western Region", "Yas Island", "Zayed Sports City",
//              ],
//              'Ajman' => [
//                  "Ajman City Center", "Ajman Corniche", "Ajman Free Zone", "Ajman Industrial Area 1 ",
//                  "Ajman Industrial Area 2 ", "Ajman Pearl", "Ajman University", "Al Alia", "Al Bustan", "Al Butain",
//                  "Al Hamidiya", "Al Hamidiya 1", "Al Hamidiya 2", "Al Helio", "Al Heliow 1", "Al Heliow 2", "Al Jurf 1",
//                  "Al Jurf 2", "Al Jurf Industrial Area 1", "Al Jurf Industrial Area 2", "Al Jurf Industrial Area 3",
//                  "Al Muntazi 1", "Al Muntazi 2", "Al Mushairef", "Al Mwaihat 1", "Al Mwaihat 2", "Al Mwaihat 3", "Al Nakhil",
//                  "Al Nakhil 1", "Al Nakhil 2", "Al Nuaimia 1", "Al Nuaimia 2", "Al Raqaib 1", "Al Raqaib 2", "Al Rashidiya 1",
//                  "Al Rashidiya 2", "Al Rashidiya 3", "Al Rawda 1 Al Zahraa", "Al Rawda 2 Al Zahraa", "Al Rawda 3 Al Zahraa",
//                  "Al Rumailah", "Al Tallah 1", "Al Tallah 2", "Al Yasmeen", "Al Zahya", "Al Zawarah", "Al Zora",
//                  "Emirates City", "Garden City", "Ittihad Village",
//              ],
//              'Al Ain' => [
//                  "Abu Samrah", "Al Agabiyya", "Al Ain International Airport", "Al Ain Zoo", "Al Ameriya", "Al Bateen",
//                  "Al Dhahir", "Al Foaa", "Al Hili", "Al Jahili", "Al Jimi", "Al Khabisi", "Al Kuwaitat", "Al Manasir",
//                  "Al Maqam", "Al Marakhaniya", "Al Masoudi", "Al Murabaa", "Al Muraijeb", "Al Mutarad", "Al Mutawaa",
//                  "Al Muwaiji", "Al Nabagh", "Al Neyadat", "Al Qattara", "Al Sad", "Al Salamat District", "Al Sarooj",
//                  "Al Towayya", "Al Yahar", "Alain Al Fiyada", "Asharej", "Bedda Bn Ammar", "Falaj Hazzaa",
//                  "Industrial Area", "Khatim Al Shikla", "Mezyed", "Mubzara", "Neima", "Remah", "Tawam", "UAE University",
//                  "Um Ghaffa", "Zakher",
//              ],
//              'Dubai' => [
//                  "Abu Hail", "Academic City", "Al Awir", "Al Bada'a", "Al Baraha", "Al Barari", "Al Barsha 1",
//                  "Al Barsha 2", "Al Barsha 3", "Al Barsha South", "Al Dhagaya", "Al Furjan", "Al Garhoud", "Al Hamriya",
//                  "Al Hudaiba", "Al Jaddaf", "Al Jaffiliya", "Al Karama", "Al Khabaisi", "Al Khawaneej 1", "Al Khawaneej 2",
//                  "Al Mamzar", "Al Manara", "Al Mankhool", "Al Mina", "Al Mizhar 1", "Al Mizhar 2", "Al Muraqqabat",
//                  "Al Murar", "Al Mushrif", "Al Muteena", "Al Nahda 1", "Al Nahda 2", "Al Quoz 1", "Al Quoz 2",
//                  "Al Quoz 3", "Al Quoz 4", "Al Quoz Industrial Area 1", "Al Quoz Industrial Area 2",
//                  "Al Quoz Industrial Area 3", "Al Quoz Industrial Area 4", "Al Qusais 1", "Al Qusais 2", "Al Qusais 3",
//                  "Al Qusais Industrial Area 1", "Al Qusais Industrial Area 2", "Al Qusais Industrial Area 3",
//                  "Al Qusais Industrial Area 4", "Al Qusais Industrial Area 5", "Al Raffa", "Al Ras", "Al Rashidiya",
//                  "Al Rigga", "Al Sabkha", "Al Safa", "Al Safa 2", "Al Satwa", "Al Shindagha", "Al Souq Al Kabeer",
//                  "Al Sufouh 1", "Al Sufouh 2", "Al Twar 1", "Al Twar 2", "Al Twar 3", "Al Waheda", "Al Warqa 1",
//                  "Al Warqa 2", "Al Warqa 3", "Al Warqa 4", "Al Warqa 5", "Al Wasl", "Arabian Ranches", "Arabian Ranches 2",
//                  "Arjan", "Barsha Heights - TECOM", "Bukadra", "Business Bay", "Corniche Deira", "DIFC", "Discovery Gardens",
//                  "Downtown Burj Khalifa", "Downtown Jabel Ali", "Dubai Airport Freezone", "Dubai Cargo Village",
//                  "Dubai Design District", "Dubai Falcon City", "Dubai Festival City", "Dubai Healthcare City", "Dubai Hills",
//                  "Dubai International Airport", "Dubai Internet City - DIC", "Dubai Investments Park 1",
//                  "Dubai Investments Park 2", "Dubai Lifestyle City", "Dubai Marina", "Dubai Maritime City",
//                  "Dubai Media City", "Dubai Motor City", "Dubai Silicon Oasis", "Dubai Sports City", "Dubai Studio City",
//                  "Dubai Techno Park", "Dubai World Central - DWC", "Dubai World Trade Center - DWTC", "Emirates Hills",
//                  "Gardens", "Global Village", "Green Community", "Green Community Motor City", "Hatta", "Hor Al Anz",
//                  "Hor Al Anz East", "Ibn Batutta Mall", "IMPZ", "International City", "International City 2", "Jebel Ali 1",
//                  "Jebel Ali 2", "Jebel Ali Freezone", "Jebel Ali Freezone Extension", "Jebel Ali Industrial Area",
//                  "Jumeirah 1", "Jumeirah 2", "Jumeirah 3", "Jumeirah Beach Residence - JBR", "Jumeirah Golf Estates",
//                  "Jumeirah Heights", "Jumeirah Islands", "Jumeirah Lakes Towers - JLT", "Jumeirah Park",
//                  "Jumeirah Village Circle - JVC", "Jumeirah Village Triangle - JVT", "Knowledge Village", "Layan Community",
//                  "Legends", "Liwan", "Majan", "MBR- Al Merkad", "Meadows", "Meydan South", "Mira Community", "Mirdif",
//                  "Mudon", "Muhaisnah 1", "Muhaisnah 2", "Muhaisnah 3", "Muhaisnah 4", "Nad Al Sheba 1", "Nad Al Sheba 2",
//                  "Nad Al Sheba 3", "Nad Al Sheba 4", "Nadd Al Hamar", "Nadd Al Shamma", "Naif", "Oud Al Muteena",
//                  "Oud Metha", "Port Rashid", "Port Saeed", "Ras Al Khor", "Ras Al Khor Indsutrial Area 1",
//                  "Ras Al Khor Indsutrial Area 2", "Ras Al Khor Indsutrial Area 3", "Remraam", "Rigga Al Buteen", "Springs",
//                  "The Greens", "The Lakes", "The Palm Deira", "The Palm Jebel Ali", "The Palm Jumeirah", "The Skycourts",
//                  "The Sustainable City", "The Villa", "Um Al Sheif", "Umm Hurair 1", "Umm Hurair 2", "Umm Ramool",
//                  "Umm Suqeim 1", "Umm Suqeim 2", "Umm Suqeim 3", "Wadi Alamardi", "Warsan 1", "Warsan 2", "Waterfront",
//                  "Za'abeel 1", "Za'abeel 2",
//              ],
//              'Fujairah' => [
//                  "Al Aqah", "Al Bedia ", "Al Buthna ", "Al Farfar", "Al Faseel", "Al Gurfa", "Al Hala ", "Al Haray",
//                  "Al Heel ", "Al Ittihad", "Al Mahatta", "Al Owaid", "Al Qurayya", "Al Taween", "Albeledah", "Anajaimat",
//                  "Awhala ", "Dedna", "Dibba", "Dibba Al Hisn", "Dibba Industrial Area", "Fujairah Free Trade Zone",
//                  "Fujairah Intl Airport", "Fujairah Port", "Halefaath", "Industrial Area", "Kalba", "Karsha", "Khor Fakkan",
//                  "Madhab", "Masafi", "Merashid", "Mirbah", "Old Fujairah City", "Qidfa", "Rughaylat", "Rumailah",
//                  "Sakamkam", "Sharm ", "Suwayfah", "Zubara",
//              ],
//              'Ras Al Khaimah' => [
//                  "Al Darbijaniyah", "Al Dhait North", "Al Dhait South", "Al Duhaisah", "Al Fahlain", "Al Ghubb",
//                  "Al Hamra Free Zone", "Al Hamra Industrial Area", "Al Hamra Island", "Al Hamra Village", "Al Hudaibah",
//                  "Al Jazeerah Al Hamra", "Al Jesser Area", "Al Juwais Area", "Al Kharran", "Al Mairid", "Al Marjan Island",
//                  "Al Mataf", "Al Nadiyah", "Al Nakheel Area", "Al Nudood", "Al Qurm", "Al Qusaidat", "Al Ragibah",
//                  "Al Sall", "Al Seer", "Al Soor", "Al Turfah", "Al Uraibi", "Al Zahra", "Burairaat", "Dafan Al Khor",
//                  "Dafan Al Nakheel", "Dahan", "Digdagga", "Ghalilah", "Hamrania", "Khatt", "Khazam", "Liwa Badr", "Mamoora",
//                  "Mina Al arab", "RAK City", "Rams", "Ras Al Selaab Area", "Refa`ah", "Seih Al Ghubb", "Seih al Harf",
//                  "Seih Al Hudaibah", "Seih Al Qusaidat", "Seih Al Uraibi", "Seih Shihyar", "Shamal Haqueel",
//                  "Shamal Julphar", "Shareesha", "Sidroh", "Suhaim Area", "Wadi Ammar",
//              ],
//              'Sharjah' => [
//                  "Abu Shagara", "Al  Muntazah", "Al Abar", "Al Atain", "Al Azra", "Al Bataeh", "Al Bdai'a Subrub",
//                  "Al Darari", "Al Dhaid", "Al Elyash", "Al Falah Suburb", "Al Falaj", "Al Fayha", "Al Fisht", "Al Ghaphia",
//                  "Al Gharayen", "Al Ghubaiba", "Al Ghuwair", "Al Goaz", "Al Hazana", "Al Homaa", "Al Jazzat", "Al Jubail",
//                  "Al Juraina", "Al Khaledia Suburb", "Al Khan", "Al Khezamia", "Al Layyah", "Al Mahatta", "Al Majaz 1",
//                  "Al Majaz 2", "Al Majaz 3", "Al Mamzar", "Al Manakh", "Al Manazel", "Al Mansura", "Al Mareija", "Al Mirgab",
//                  "Al Mujarah", "Al Musalla", "Al Nabba", "Al Nad", "Al Nahda", "Al Nasserya", "Al Nekhailat", "Al Noof",
//                  "Al Qadisia", "Al Qasimia", "Al Qulayaa", "Al Rahmania", "Al Ramaqia", "Al Ramla East", "Al Ramla West",
//                  "Al Ramtha", "Al Rifah", "Al Riffa", "Al Sabkha", "Al Seef", "Al Seyouh", "Al Shahba", "Al Shuwaihen",
//                  "Al Soor", "Al Sweihat", "Al Taawun", "Al Talaa", "Al Tarfa", "Al Yarmook", "Barashi", "Bu Danig",
//                  "Bu Tina", "Dasman", "Industrial Area 1", "Industrial Area 10", "Industrial Area 11", "Industrial Area 12",
//                  "Industrial Area 13", "Industrial Area 15", "Industrial Area 17", "Industrial Area 18", "Industrial Area 2",
//                  "Industrial Area 3", "Industrial Area 4", "Industrial Area 5", "Industrial Area 6", "Industrial Area 7",
//                  "Industrial Area 8", "Industrial Area 9", "Maysaloon", "Muwafjah", "Muwaileh Commercial", "Muzairah",
//                  "Rolla", "Saif Zone", "Samnan", "Sharqan", "Um Altaraffa", "University of Sharjah",
//              ],
//              'Um Al Quwain' => [
//                  "Al Aahad", "Al Abrab", "Al Dar Al Baidah", "Al Haditha", "Al Hawiyah", "Al Hobob", "Al Humrah - A",
//                  "Al Humrah - B", "Al Humrah - C", "Al Humrah - D", "Al Khor", "Al Limgadhar", "Al Maidan", "Al Qarain",
//                  "Al Raas - A", "Al Raas - B", "Al Raas - C", "Al Rafaah", "Al Ramlah", "Al Raudah", "Al Riqqah",
//                  "Al Salamah - A", "Al Salamah - B", "Al Salamah - C", "Defence Camp", "Emirates Modern Industrial",
//                  "Green Belt", "Industrial Area", "Khalifa City", "Latin", "Mohamed Bin Rashed", "Old Town Area",
//                  "Umm Al Quwain Airport", "Umm Al Quwain Marina",
//              ]
//          ];
//      }
//  }




?>